### ISSUE TITLE
Adressable dependency is too restrictive

### ISSUE THREAD

**Issue by hugoluchessi** [altmetric/embiggen#34]
Hi, I trying to add a gem to my code and the restriction to addressable `~> 2.3` is blocking it.

Is there any problem to bump it to version 2.5?

**Comment by mudge** [comment]
Hi @hugoluchessi,

Our runtime dependency on Addressable is a [pessimistic version constraint](http://guides.rubygems.org/patterns/#pessimistic-version-constraint) and so should support all versions of Addressable from 2.3.0 up to (but not including) 3.0.

Are you getting an error from Bundler trying to install Embiggen and Addressable 2.5?

**Comment by hugoluchessi** [comment]
Sorry, it was another dependency problem.

You can close this issue.

Thanks for the quick response =)
