### ISSUE TITLE
Return original URL if host is unreachable

### ISSUE THREAD

**Issue by omartell** [altmetric/embiggen#5]
As embiggen handles `Timeout::Error` and `Errno::ECONNRESET`, was wondering if it should also handle 
[`Errno::EHOSTUNREACH`](http://ruby-doc.org/stdlib-1.8.7/libdoc/socket/rdoc/Socket.html#method-i-connect-label-Unix-based+Exceptions) and return the original URL.

**Comment by omartell** [comment]
It might also be worth rescuing  `Errno::TIMEDOUT`.

**Comment by mudge** [comment]
If we switch to the API in #3, we could rescue all descendants of `StandardError` rather than having to play whack a mole with the various exception types that could be raised by `Net::HTTP`.

**Comment by omartell** [comment]
Makes sense, let's not get into exceptions "guacamole".

**Comment by mudge** [comment]
Fixed in 0.1.1.
